### ISSUE TITLE
argc == 2

### ISSUE THREAD

**Issue by S3Jon** [Thuggonaut/42IC_Ring02_Push_swap#1]
Hello!
Your video about the push_swap was beautifully made, it helped me a lot, but I was left with a little question.
When all the numbers are contained within argv[1], you call split and it mallocs them, but then there is no check to free when argc is 2?
Maybe I missed it.

Cheers.

**Comment by Thuggonaut** [comment]
Hello there :) 

Thank you so much for the kind words.

I'm not too sure what you mean by "but then there is no check to free when argc is 2?" but I'll try my best!

- argc must be 2 if argv[1] is a string, and must not be empty for it to call split(). 

- my split() mallocs but doesn't free things, it's only responsible for splitting a string, and returns NULL at any point malloc is unsuccessful, otherwise it returns a populated array, which init_stack_a() can work with. 

- init_stack_a() is where errors are handled, and frees the stack if there are errors at any point of appending each node. 

- in main, push_swap.c,  we call split() on argv[1], and if successful, it progresses to initialization. If unsuccessful and split() returns NULL, it will skip the next code block and progresses to freeing the stack. 

I'm not sure I answered your question... please let me know if I didn't, and If I misunderstood something. 

Thanks again for visiting, and good luck with push_swap! :)

**Comment by S3Jon** [comment]
Sorry, I really messed up the question haha.
I'll give an example:

- If I do ./push_swap 5 4 3 2 1, each number is a separate argument, so split is not needed.
- But if I do ./push_swap "5 4 3 2 1", split would have to be called. (This is what I meant with argc == 2, my bad)

In your code, you store the array split returns in argv, to then send it to initiate stack_a and so on, but argv is not freed after? (Maybe I missed it, sorry if that's the case).

If freeing was actually needed, since argc would still be equal to 2, we'd just need to check if the length of argv is greater than 2 to tell when.

**Comment by Thuggonaut** [comment]
I see. No no it's my bad, it's me being too noob to understand you, haha. 

You're right, my code doesn't free argv. Someone mentioned that my code had memory leaks because my split() doesn't free memory. I didn't bother to test for it since the program works and does its job to pass the evaluation - though in the real world, it'd be neccessary to properly free things. 

I could be wrong, but I think argv is automatically freed by the system after the program exits. But you're right in that we need to properly free the memory allocated by split() for individual substrings.

In main, after the sorting block and before freeing the stack, we could do something like:
```
int i = 0;
while (argv[i]) 
{
    free(argv[i]);
    i++;
}
free(argv); 
```
Maybe as a helper function, since adding this would make our code 25+ lines. 

Was this along the lines of your thoughts/question? Wish I was more helpful, sorry!

**Comment by S3Jon** [comment]
Yeah, that was my question. 
From your project I was wondering if argv freed itself on program exit too, but everywhere I looked said it doesn't so I opened the Issue.

Thanks for the clarification 😄

**Comment by Thuggonaut** [comment]
Thank you for bringing it up! It definitely helps me learn better :)
